package com.sherpasteven.sscte.Models;

import android.content.Context;
import android.provider.Settings;

/**
 * This class is used to uniquely identify different users.
 * The id is generated by using the android API to get the
 * ANDROID_ID. This means that the profile has exactly one
 * unique instance per phone.
 */
public class ProfileId {

    private String id;

    public ProfileId(Context context){
        //TODO(Put this in referenced sources)
        //Anthony Forloney, http://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id
        id = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID);
    }

    public String GetId(){
        return id;
    }

    @Override
    public boolean equals(Object other){
        if (!(other instanceof ProfileId)) return false;
        ProfileId otherProfileId = (ProfileId) other;
        return this.GetId().equals(otherProfileId.GetId());
    }
}
